name: Run tests

on:
  schedule:
    - cron: 0 * * * *
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        mkdir vegeta
        cd vegeta
        curl -LO https://github.com/tsenart/vegeta/releases/download/v6.1.1/vegeta-v6.1.1-linux-amd64.tar.gz
        tar -xvf vegeta-*
        mv vegeta /bin/vegeta
        cd ..
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      env:
        API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
      run: |
        python run.py
